---
- name: Просто печатаем сообщения
  hosts: webservers
  gather_facts: yes

  tasks:
    - name: Приветственное сообщение
      debug:
        msg: "ыоадлоыдлаодвыоадоывДЛВОАЛДВОДЛАОывдоаылдв"

    - name: Ответочка
      debug:
        msg: "Пвоыпдоыладлы"